name: palimpsest
description: A mobile game built around the feeling of watching a hard drive defragment in the 90s
version: 0.0.0
publish_to: none

repository: https://github.com/ghaiklor/palimpsest

environment:
  sdk: 3.11.3
