name: Flutter Build

on:
  push:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: subosito/flutter-action@v2.22.0
        with:
          cache: true
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter analyze
