name: Flutter Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: subosito/flutter-action@v2.22.0
        with:
          cache: true
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter analyze
      - run: flutter test --coverage --test-randomize-ordering-seed random --reporter github
      - run: flutter build ios --build-number ${{ github.sha }} --no-codesign
